version: 2

project_name: nwx-cli

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: nwx

archives:
  - files:
      - README.md
      - LICENSE*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'


snapshot:
  version_template: "{{ incpatch .Version }}-next"

brews:
  - name: netwrix
    homepage: "https://github.com/netwrix/nwx-cli"
    description: "Netwrix CLI - Under Construction"
    repository:
      owner: netwrix
      name: homebrew-tap
    commit_author:
      name: netwrix-bot
      email: ai@netwrix.com
    install: |
      bin.install "nwx"
    test: |
      system "#{bin}/nwx"